# Stage 1: Build
FROM node:22 AS builder
WORKDIR /app

COPY package*.json ./
RUN npm ci  # cleaner, faster install for prod
COPY . .
RUN npm run build

# Stage 2: Run
FROM node:22-slim AS production
WORKDIR /app

COPY --from=builder /app/.next ./.next
COPY --from=builder /app/node_modules ./node_modules
COPY --from=builder /app/public ./public
COPY --from=builder /app/package*.json ./

EXPOSE 3007
CMD ["npm", "start"]
