# Use an official Node.js runtime as a parent image
FROM node:21

# Set the working directory in the container
WORKDIR /app

# Copy package.json and package-lock.json to the container
COPY package*.json ./

# Install dependencies
RUN npm install 
COPY . .

# Expose ports for both Next.js and the backend server
EXPOSE 3007

# Default command (can be overridden in docker-compose)
CMD ["sh", "-c", " npm run dev"]
