# Use an official Node.js runtime as a parent image
FROM node:22

# Set the working directory in the container
WORKDIR /app

# Copy package.json and package-lock.json first to leverage caching
COPY package*.json ./

# Install dependencies
RUN npm install --legacy-peer-deps && npm cache clean --force

# Copy the rest of the application files
COPY . .

# Ensure next.js build is done before running
RUN npm run build

# Expose necessary port
EXPOSE 3007

# Default command to start the app
CMD ["npm", "run", "dev"]
