version: '3.8'

services:
  frontend-dev:
    build:
      context: .
      dockerfile: Dockerfile.dev
    restart: always
    volumes:
      - .:/app
      - /app/node_modules  # Keep node_modules isolated
    ports:
      - "3007:3007"
    environment:
      # Environment mode
      - NODE_ENV=development
      - WATCHPACK_POLLING=true
      
      # API Configuration
      - BASE_URL=http://localhost:8090
      
      # Socket Configuration
      - BR_WLMS_SOCKET_URL=http://localhost:3001
      - TR_WLMS_SOCKET_URL=http://localhost:3004
      - SAATHI_TX_SOCKET_URL=http://localhost:3005
      - SAATHI_RX_SOCKET_URL=http://localhost:3006
      - RAILTAAP_SOCKET_URL=http://localhost:3009
      - TANK_WLMS_SOCKET_URL=http://localhost:3010
      - MQTT_URL=ws://localhost:9001/ws
      
      # Database
      - DB_URL=mysql://root:inRKI@0510@49.50.119.39:3306/railkriti_db
      
      # Auth Configuration
      - PORT=3007
      - AUTH_SECRET=Q29tbWFuZCB0byBnZW5lcmF0ZSBhIHJhbmRvbSBzdHJpbmcgaW4gYmFzZTY0
      - EMAIL=info@robokriti.com
      - PASSWORD=hqbaevkbtsgkhuav
      - CLIENT_SECRET=hkfgfhfkjhf
      - NEXTAUTH_URL=http://localhost:3007
      
      # Other
      - USE_HTTPS=false
    command: ["sh", "-c", "npm run dev"]

  frontend-prod:
    build:
      context: .
      dockerfile: Dockerfile.prod
    restart: unless-stopped
    ports:
      - "3007:3007"
    environment:
      # Environment mode
      - NODE_ENV=production
      
      # API Configuration
      - BASE_URL=https://railkriti.co.in:8090
      
      # Socket Configuration
      - BR_WLMS_SOCKET_URL=https://railkriti.co.in:3001
      - TR_WLMS_SOCKET_URL=https://railkriti.co.in:3004
      - SAATHI_TX_SOCKET_URL=https://railkriti.co.in:3005
      - SAATHI_RX_SOCKET_URL=https://railkriti.co.in:3006
      - RAILTAAP_SOCKET_URL=https://railkriti.co.in:3009
      - TANK_WLMS_SOCKET_URL=https://railkriti.co.in:3010
      - MQTT_URL=wss://railkriti.co.in:9002/ws
      
      # Database
      - DB_URL=mysql://root:inRKI@0510@49.50.119.39:3306/railkriti_db
      
      # Auth Configuration
      - PORT=3007
      - AUTH_SECRET=Q29tbWFuZCB0byBnZW5lcmF0ZSBhIHJhbmRvbSBzdHJpbmcgaW4gYmFzZTY0
      - EMAIL=info@robokriti.com
      - PASSWORD=hqbaevkbtsgkhuav
      - CLIENT_SECRET=hkfgfhfkjhf
      # - NEXTAUTH_URL=https://railkriti.co.in
      - NEXTAUTH_URL=http://localhost:3007
      # Other
      - USE_HTTPS=true
    command: ["npm", "start"]

